"""Evidence-gated paper authority.

The operational pipeline, not legacy momentum-only paper_step(), is the authority
for new paper capital. Missing valuation/prediction/risk evidence freezes new
allocation instead of silently falling back to weaker logic.
"""
from __future__ import annotations

from typing import Any

from radar_core import con, now, paper_status
from radar_operational_pipeline_v1 import operational_pipeline

REAL_TRADING=False


def paper_authority_step(force:bool=False)->dict[str,Any]:
    account=paper_status()
    if not account.get('configured') or not account.get('enabled'):
        return {'status':'INACTIVE','reason':'PAPER_ACCOUNT_NOT_ENABLED','paper':account,'allocations':[],
                'authority':'OPERATIONAL_PIPELINE_V1','can_trade':False,'real_trading':False}
    pipeline=operational_pipeline(); optimizer=pipeline.get('optimizer') or {}; allocations=list(optimizer.get('allocations') or [])
    if optimizer.get('status')!='READY' or not allocations:
        return {'status':'HOLD_EXISTING_NO_NEW_RISK','reason':optimizer.get('reason') or optimizer.get('status') or 'INSUFFICIENT_EVIDENCE',
                'paper':account,'allocations':[],'authority':'OPERATIONAL_PIPELINE_V1','legacy_momentum_fallback':False,
                'can_trade':False,'real_trading':False}
    # Paper-only execution. Allocation amounts are generated by optimizer v3 and capped there.
    prices={x.get('symbol'):x.get('price') for x in (pipeline.get('market_telemetry') or {}).get('assets',[]) if x.get('price')}
    held={p['symbol']:p for p in account.get('positions',[])}; executed=[];c=con()
    try:
        cash=float(account.get('cash') or 0)
        for alloc in allocations:
            symbol=str(alloc.get('symbol') or ''); amount=float(alloc.get('amount') or 0); price=float(prices.get(symbol) or 0)
            if not symbol or amount<=0 or price<=0 or symbol in held or cash<amount:continue
            qty=amount/price
            c.execute('update paper_account set cash=cash-? where id=1',(amount,))
            c.execute('insert or replace into paper_positions(symbol,qty,avg_price,updated_at) values(?,?,?,?)',(symbol,qty,price,now()))
            c.execute('insert into paper_trades(ts,symbol,side,qty,price,value,reason) values(?,?,?,?,?,?,?)',
                      (now(),symbol,'BUY',qty,price,amount,'OPERATIONAL_PIPELINE_V1_OPTIMIZER_V3'))
            cash-=amount;executed.append({'symbol':symbol,'amount':amount,'qty':qty,'price':price})
        c.execute('update paper_account set last_rebalance=? where id=1',(now(),));c.commit()
    finally:c.close()
    updated=paper_status();c=con();c.execute('insert into portfolio_values(ts,total,cash,invested) values(?,?,?,?)',(now(),updated['total'],updated['cash'],updated.get('invested',0)));c.commit();c.close()
    return {'status':'PAPER_ALLOCATED' if executed else 'HOLD_EXISTING_NO_NEW_RISK','paper':updated,'allocations':executed,
            'authority':'OPERATIONAL_PIPELINE_V1','legacy_momentum_fallback':False,'can_trade':False,'real_trading':False}
