"""Live runtime evidence board for autonomous PAPER tasks 21-30.

This module reads production PAPER evidence already generated by the runtime. It never
backfills observations, invents maturity, promotes a challenger, submits broker orders,
or enables live trading. Missing evidence stays PENDING/NOT_VERIFIED.
"""
from __future__ import annotations

from datetime import datetime, timezone

import radar_decision_memory_v2 as decision_memory
import radar_forward_evidence_v2 as forward
import radar_attribution_v3 as attribution
import radar_simulator_hardening_16_25_v1 as hard

REAL_TRADING = False


def _now(): return datetime.now(timezone.utc).isoformat()


def task21_decision_journal():
    try:
        h = decision_memory.memory_health()
        episodes = int(h.get('episodes') or 0); evaluated = int(h.get('evaluated') or 0)
        status = 'PASS' if episodes > 0 else 'PENDING_SAMPLE'
        return {'task':21,'name':'decision_journal','status':status,'episodes':episodes,
                'evaluated':evaluated,'append_only_memory':True,'future_evidence_allowed':False,
                'automatic_promotion':False,'real_trading':False}
    except Exception as exc:
        return {'task':21,'name':'decision_journal','status':'NOT_VERIFIED','error':f'{type(exc).__name__}: {str(exc)[:500]}','real_trading':False}


def task22_forward_horizons():
    try:
        snap = forward.forward_evidence_snapshot()
        horizons = snap.get('horizons') or {}
        return {'task':22,'name':'forward_horizons','status':'PASS' if horizons and all(v.get('status')=='PASS' for v in horizons.values()) else 'PENDING_FORWARD_MATURITY',
                'horizons':horizons,'backfill_allowed':False,'real_trading':False}
    except Exception as exc:
        return {'task':22,'name':'forward_horizons','status':'NOT_VERIFIED','error':f'{type(exc).__name__}: {str(exc)[:500]}','real_trading':False}


def task23_forward_attribution():
    try:
        rows = [r for r in forward.canonical_forward_rows() if r.get('matured') is True and r.get('natural') is True]
        packed=[]
        for r in rows:
            outcome=r.get('outcome') or {}
            packed.append({'gross_return_pct':r.get('raw_return'),
                           'benchmark_return_pct':r.get('benchmark_return'),
                           'costs_pct':r.get('cost'),
                           'timing_effect_pct':outcome.get('timing_effect_pct'),
                           'sizing_effect_pct':outcome.get('sizing_effect_pct'),
                           'fx_effect_pct':outcome.get('fx_effect_pct'),
                           'sector_effect_pct':outcome.get('sector_effect_pct'),
                           'beta_effect_pct':outcome.get('beta_effect_pct'),
                           'cash_effect_pct':outcome.get('cash_effect_pct')})
        s=attribution.attribution_summary_v3(packed)
        status='PASS' if s.get('records',0)>0 and s.get('coverage')==1 else ('PARTIAL' if s.get('attributable',0)>0 else 'PENDING_SAMPLE')
        return {'task':23,'name':'forward_attribution','status':status,'summary':s,'performance_verified':False,'real_trading':False}
    except Exception as exc:
        return {'task':23,'name':'forward_attribution','status':'NOT_VERIFIED','error':f'{type(exc).__name__}: {str(exc)[:500]}','real_trading':False}


def task24_meta_learning():
    return {'task':24,'name':'bounded_meta_learning','status':'GOVERNED_PENDING_SAMPLE',
            'challenger_only':True,'bounded_mutation_required':True,'historical_can_promote':False,
            'automatic_promotion':False,'automatic_champion_replacement':False,'real_trading':False}


def task25_scorecard(simulator_status, milestones, restore, lease):
    paper=(simulator_status or {}).get('paper') or {}
    metrics={'uptime_pct':None,'cycles':(simulator_status or {}).get('completed_cycles'),
             'decisions':None,'trades':paper.get('trades'),'abstentions':None,
             'equity':paper.get('total'),'pnl':paper.get('pnl_pct'),'max_drawdown':paper.get('max_drawdown'),
             'costs':paper.get('costs'),'errors':1 if (simulator_status or {}).get('last_error') else 0,
             'recoveries':1 if (restore or {}).get('status')=='RESTORED_EXACT_PAPER_ENGINE' else 0,
             'persistence_integrity':bool((restore or {}).get('verified')),
             'valid_forward_hours':(milestones or {}).get('elapsed_hours'),
             'return_observations':0,'sharpe':None,'sortino':None}
    return {'task':25,'name':'paper_scorecard','status':'OBSERVING','metrics':metrics,
            'milestones':milestones,'lease_status':(lease or {}).get('status'),'real_trading':False}


def task26_lease_continuity(lease):
    l=lease or {}; held=l.get('held') is True or l.get('status')=='HELD'
    return {'task':26,'name':'lease_continuity','status':'PASS' if held else 'FAIL_CLOSED',
            'held':held,'reacquired':bool(l.get('reacquired')),'error':l.get('error'),
            'duplicate_instances_allowed':False,'real_trading':False}


def task27_exact_restore(restore):
    r=restore or {}; ok=(r.get('status')=='RESTORED_EXACT_PAPER_ENGINE' and r.get('verified') is True and
        bool(r.get('remote_state_hash')) and r.get('remote_state_hash')==r.get('local_state_hash') and
        r.get('backfill_used') is False and r.get('reconstructed') is False and r.get('real_trading') is False)
    return {'task':27,'name':'exact_restore','status':'PASS' if ok else 'FAIL_CLOSED',
            'verified':bool(r.get('verified')),'hash_equal':bool(r.get('remote_state_hash')) and r.get('remote_state_hash')==r.get('local_state_hash'),
            'schema_version':r.get('local_schema_version'),'backfill_used':r.get('backfill_used'),
            'reconstructed':r.get('reconstructed'),'real_trading':False}


def task28_reconciliation(local, remote):
    required=('state_hash','session_id','cycle','cash','equity','positions_hash','learning_hash','observed_at')
    missing_local=[k for k in required if (local or {}).get(k) is None]
    missing_remote=[k for k in required if (remote or {}).get(k) is None]
    if missing_local or missing_remote:
        return {'task':28,'name':'persistence_reconciliation','status':'NOT_VERIFIED',
                'missing_local':missing_local,'missing_remote':missing_remote,
                'silent_overwrite_allowed':False,'new_paper_risk_allowed':False,
                'live_execution_allowed':False,'real_trading':False}
    try:return {'task':28,'name':'persistence_reconciliation',**hard.persistence_reconciliation_gate(local,remote)}
    except Exception as exc:return {'task':28,'name':'persistence_reconciliation','status':'NOT_VERIFIED','error':f'{type(exc).__name__}: {str(exc)[:500]}','real_trading':False}


def task29_disaster_evidence(results=None):
    gate=hard.disaster_test_gate(results or [])
    return {'task':29,'name':'disaster_evidence',**gate,'synthetic_evidence_counts':False}


def task30_composite(tasks):
    blockers=[]
    acceptable={21:{'PASS'},22:{'PASS'},23:{'PASS'},24:{'GOVERNED_PENDING_SAMPLE','PASS'},25:{'OBSERVING','PASS'},26:{'PASS'},27:{'PASS'},28:{'RECONCILED'},29:{'PASS'}}
    for t in tasks:
        n=t.get('task'); st=t.get('status')
        if n in acceptable and st not in acceptable[n]: blockers.append(f'{n}:{st}')
    return {'task':30,'name':'production_paper_gate_21_30','status':'PASS' if not blockers else 'PENDING',
            'blockers':blockers,'paper_only':True,'live_execution_allowed':False,
            'automatic_promotion':False,'automatic_release':False,'setup_1_6_allowed':False,'real_trading':False}


def board(*, simulator_status=None, milestones=None, restore=None, lease=None,
          reconciliation_local=None, reconciliation_remote=None, disaster_results=None):
    tasks=[task21_decision_journal(),task22_forward_horizons(),task23_forward_attribution(),task24_meta_learning(),
           task25_scorecard(simulator_status or {},milestones or {},restore or {},lease or {}),
           task26_lease_continuity(lease or {}),task27_exact_restore(restore or {}),
           task28_reconciliation(reconciliation_local or {},reconciliation_remote or {}),
           task29_disaster_evidence(disaster_results or [])]
    tasks.append(task30_composite(tasks))
    return {'generated_at':_now(),'tasks':tasks,'live_execution_allowed':False,'automatic_promotion':False,
            'automatic_release':False,'setup_1_6_allowed':False,'real_trading':False}
