import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const EXPECTED_HASH="1e96928c7781f339732602234a1047fd510e38de04768d171884166ba5ae91e3";
const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const WRITE_CONCURRENCY=20;
async function sha(s:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function res(code:number,p:any){return new Response(JSON.stringify(p),{status:code,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function sameNumeric(a:any,b:any,tolerance=1e-6){if(a==null||b==null)return a==null&&b==null;const x=Number(a),y=Number(b);return Number.isFinite(x)&&Number.isFinite(y)&&Math.abs(x-y)<=tolerance}
async function agentMap(){const {data,error}=await sb.from("paper_agents").select("id,slug");if(error)throw error;const m:any={};for(const r of data||[])m[r.slug]=r.id;return m}
async function mapConcurrent<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>):Promise<R[]>{const out:R[]=[];const size=Math.max(1,Math.min(50,Number(limit)||1));for(let i=0;i<items.length;i+=size){const chunk=items.slice(i,i+size);out.push(...await Promise.all(chunk.map(fn)))}return out}
Deno.serve(async(req)=>{const started=Date.now();try{const token=req.headers.get("x-radar-token")||"";if(!token||await sha(token)!==EXPECTED_HASH)return res(401,{ok:false,error:"unauthorized"});if(req.method==="GET"){const [{count:market},{count:events},{count:runs},{count:alerts},{data:agents}]=await Promise.all([sb.from("market_snapshots").select("id",{count:"exact",head:true}),sb.from("information_events").select("id",{count:"exact",head:true}),sb.from("system_runs").select("id",{count:"exact",head:true}),sb.from("silence_alerts").select("id",{count:"exact",head:true}),sb.from("paper_agents").select("slug,name,profile,initial_cash,cash,enabled,updated_at,last_rebalance").order("slug")]);return res(200,{ok:true,counts:{market:market||0,events:events||0,runs:runs||0,alerts:alerts||0},agents:agents||[],edge_ms:Date.now()-started})}if(req.method!=="POST")return res(405,{ok:false,error:"method_not_allowed"});const b=await req.json().catch(()=>({}));const out:any={ok:true,write_concurrency:WRITE_CONCURRENCY};
const market=Array.isArray(b.market_snapshots)?b.market_snapshots.slice(0,1000):[];if(market.length){const rows=market.map((x:any)=>({ts:x.ts,symbol:x.symbol,price:x.price,volume:x.volume??null,source:x.source||"unknown",currency:x.currency??null,metadata:x.metadata||{},origin_node:x.origin_node||b.node_id||"cloud",origin_id:x.origin_id??x.id??null}));const {error}=await sb.from("market_snapshots").upsert(rows,{onConflict:"origin_node,origin_id",ignoreDuplicates:true});if(error)throw error;out.market_snapshots=rows.length}
const rawEvents=Array.isArray(b.information_events)?b.information_events.slice(0,1000):[];const eventSeen=new Set<string>();const events=rawEvents.filter((x:any)=>{if(!x?.title)return false;if(!x.url)return true;const key=String(x.source||"unknown")+"\u0000"+String(x.url);if(eventSeen.has(key))return false;eventSeen.add(key);return true});let eventInserted=0;if(events.length){const inserted=await mapConcurrent(events,WRITE_CONCURRENCY,async(x:any)=>{const origin=x.origin_node||b.node_id||"cloud";if(x.url){const {data:existing,error:qe}=await sb.from("information_events").select("id").eq("source",x.source||"unknown").eq("url",x.url).maybeSingle();if(qe)throw qe;if(existing)return 0}const row={ts:x.ts,source:x.source||"unknown",title:x.title,url:x.url||null,category:x.category||null,symbols:x.symbols||[],topic:x.topic||null,sentiment:x.sentiment??null,novelty:x.novelty??null,metadata:x.metadata||{},origin_node:origin,origin_id:x.origin_id??x.id??null};const {error}=await sb.from("information_events").upsert(row,{onConflict:"origin_node,origin_id",ignoreDuplicates:true});if(error)throw error;return 1});eventInserted=inserted.reduce((a:number,n:number)=>a+n,0);out.information_events=eventInserted}
const runs=Array.isArray(b.system_runs)?b.system_runs.slice(0,1000):[];if(runs.length){const rows=runs.map((x:any)=>({ts:x.ts,node_id:x.node_id||b.node_id||null,kind:x.kind||x.job||"unknown",status:x.status||"unknown",message:x.message||x.detail||null,metrics:x.metrics||{},origin_node:x.origin_node||b.node_id||"cloud",origin_id:x.origin_id??x.id??null}));const {error}=await sb.from("system_runs").upsert(rows,{onConflict:"origin_node,origin_id",ignoreDuplicates:true});if(error)throw error;out.system_runs=rows.length}
const reps=Array.isArray(b.source_reputation)?b.source_reputation:[];if(reps.length){const rows=reps.map((r:any)=>({source:r.source,topic:r.topic||"global",horizon:r.horizon||"global",observations:r.events??r.observations??0,hits:r.actionable??r.hits??0,misses:Math.max(0,Number(r.events??r.observations??0)-Number(r.actionable??r.hits??0)),score:r.score??0,lead_time_hours:r.lead_time_hours??null,updated_at:r.updated_at||new Date().toISOString(),metadata:{avg_abs_move:r.avg_abs_move??null,precision_proxy:r.precision_proxy??null,confidence:r.confidence??null}})).filter((r:any)=>r.source);const {error}=await sb.from("source_reputation").upsert(rows,{onConflict:"source,topic,horizon"});if(error)throw error;out.source_reputation=rows.length}
const alerts=Array.isArray(b.silence_alerts)?b.silence_alerts.slice(0,1000):[];if(alerts.length){const rows=alerts.map((a:any)=>({created_at:a.ts||a.created_at||new Date().toISOString(),symbol:a.symbol,severity:a.severity||(Math.abs(Number(a.z_score||a.zscore||0))>=3?"HIGH":"MEDIUM"),zscore:a.z_score??a.zscore??null,price_change:a.return_pct??a.price_change??null,volume_anomaly:a.volume_anomaly??null,catalyst_found:Boolean(a.recent_public_catalyst??a.catalyst_found??false),status:String(a.status||"OPEN").toLowerCase(),explanation:a.detail||a.explanation||null,metadata:a.metadata||{},origin_node:a.origin_node||b.node_id||"cloud",origin_id:a.origin_id??a.id??null})).filter((a:any)=>a.symbol);const {error}=await sb.from("silence_alerts").upsert(rows,{onConflict:"origin_node,origin_id",ignoreDuplicates:true});if(error)throw error;out.silence_alerts=rows.length}
const notifs=Array.isArray(b.notifications)?b.notifications.slice(0,1000):[];if(notifs.length){const rows=notifs.map((n:any)=>({created_at:n.ts||n.created_at||new Date().toISOString(),kind:n.kind||"info",severity:n.severity||"info",title:n.title||"Radar",body:n.body||null,read_at:n.read?(n.read_at||n.ts||new Date().toISOString()):null,metadata:{symbol:n.symbol??null,dedupe_key:n.dedupe_key??null},origin_node:n.origin_node||b.node_id||"cloud",origin_id:n.origin_id??n.id??null}));const {error}=await sb.from("notifications").upsert(rows,{onConflict:"origin_node,origin_id",ignoreDuplicates:true});if(error)throw error;out.notifications=rows.length}
const agents=Array.isArray(b.paper_agents)?b.paper_agents:[];if(agents.length){const rows=agents.map((a:any)=>({slug:a.agent_id||a.slug,name:a.name||a.agent_id||a.slug,profile:a.strategy||a.profile||a.agent_id||a.slug,initial_cash:a.initial_cash??a.initial??200,cash:a.cash??a.initial_cash??200,enabled:a.enabled!==false&&a.enabled!==0,last_rebalance:a.last_rebalance||null,updated_at:new Date().toISOString(),settings:a.settings||{}}));const {error}=await sb.from("paper_agents").upsert(rows,{onConflict:"slug"});if(error)throw error;out.paper_agents=rows.length}const amap=await agentMap();
const pos=Array.isArray(b.paper_positions)?b.paper_positions:[];if(pos.length){const rows=pos.map((p:any)=>({agent_id:amap[p.agent_id],symbol:p.symbol,qty:p.qty,avg_price:p.avg_price,updated_at:p.updated_at||new Date().toISOString()})).filter((p:any)=>p.agent_id&&p.symbol);const {error}=await sb.from("paper_positions").upsert(rows,{onConflict:"agent_id,symbol"});if(error)throw error;out.paper_positions=rows.length}
const trades=Array.isArray(b.paper_trades)?b.paper_trades.slice(0,1000):[];if(trades.length){const rows=trades.map((t:any)=>({agent_id:amap[t.agent_id],ts:t.ts,symbol:t.symbol,side:String(t.side||'').toUpperCase(),qty:t.qty,price:t.price,fee:t.fees??t.fee??0,spread_cost:t.spread_cost??0,fx_cost:t.fx_cost??0,reason:t.reason||null,metadata:{gross_value:t.gross_value??null},origin_node:t.origin_node||b.node_id||"cloud",origin_id:t.origin_id??t.id??null})).filter((t:any)=>t.agent_id&&t.symbol&&(t.side==='BUY'||t.side==='SELL'));const {error}=await sb.from("paper_trades").upsert(rows,{onConflict:"origin_node,origin_id",ignoreDuplicates:true});if(error)throw error;out.paper_trades=rows.length}
const rawMarks=Array.isArray(b.portfolio_values)?b.portfolio_values.slice(0,1000):[];const mappedMarks=rawMarks.map((m:any)=>({agent_id:amap[m.agent_id],ts:m.ts,equity:m.total??m.equity,cash:m.cash,invested:m.invested??0,drawdown:m.drawdown_pct??m.drawdown??null,sharpe:m.sharpe??null,benchmark_value:m.benchmark_value??null,origin_node:m.origin_node||b.node_id||"cloud",origin_id:m.origin_id??m.id??null})).filter((m:any)=>m.agent_id&&m.equity!=null&&m.cash!=null);const naturalSeen=new Map<string,any>();const rows:any[]=[];for(const row of mappedMarks){const key=String(row.agent_id)+"\u0000"+String(row.ts);const prior=naturalSeen.get(key);if(prior){if(!sameNumeric(prior.equity,row.equity)||!sameNumeric(prior.cash,row.cash)||!sameNumeric(prior.invested,row.invested)||!sameNumeric(prior.drawdown,row.drawdown,1e-9))throw new Error(`portfolio_values duplicate batch mismatch agent=${row.agent_id} ts=${row.ts}`);continue}naturalSeen.set(key,row);rows.push(row)}if(rows.length){const insertedFlags=await mapConcurrent(rows,WRITE_CONCURRENCY,async(row:any)=>{const {data:existing,error:lookupError}=await sb.from("portfolio_values").select("id,equity,cash,invested,drawdown").eq("agent_id",row.agent_id).eq("ts",row.ts).maybeSingle();if(lookupError)throw lookupError;if(existing){if(!sameNumeric(existing.equity,row.equity)||!sameNumeric(existing.cash,row.cash)||!sameNumeric(existing.invested,row.invested)||!sameNumeric(existing.drawdown,row.drawdown,1e-9))throw new Error(`portfolio_values immutable mismatch agent=${row.agent_id} ts=${row.ts}`);return 0}const {data:originExisting,error:originError}=await sb.from("portfolio_values").select("id").eq("origin_node",row.origin_node).eq("origin_id",String(row.origin_id)).maybeSingle();if(originError)throw originError;if(originExisting)throw new Error(`portfolio_values origin collision node=${row.origin_node} origin_id=${String(row.origin_id)}`);const {error:insertError}=await sb.from("portfolio_values").insert(row);if(insertError)throw insertError;return 1});out.portfolio_values=insertedFlags.reduce((a:number,n:number)=>a+n,0)}
const nodes=Array.isArray(b.nodes)?b.nodes:[];if(nodes.length){await mapConcurrent(nodes,WRITE_CONCURRENCY,async(n:any)=>{if(!n?.node_id)return 0;let caps:any=n.capabilities||{};if(typeof caps==="string"){try{caps=JSON.parse(caps)}catch{caps=[caps]}}const {error}=await sb.from("radar_nodes").upsert({node_id:n.node_id,node_type:n.node_type||"other",name:n.name||null,enabled:true,app_version:n.app_version||null,last_seen:n.last_seen||new Date().toISOString(),capabilities:caps,metadata:{detail:n.detail||null}},{onConflict:"node_id"});if(error)throw error;return 1});out.nodes=nodes.length}
if(b.node?.node_id){const n=b.node;const {error}=await sb.from("radar_nodes").upsert({node_id:n.node_id,node_type:n.node_type||"other",name:n.name||null,enabled:n.enabled!==false,app_version:n.app_version||null,last_seen:n.last_seen||new Date().toISOString(),capabilities:n.capabilities||{},metadata:n.metadata||{}},{onConflict:"node_id"});if(error)throw error;out.node=n.node_id}
out.edge_ms=Date.now()-started;out.input_counts={market:market.length,events:rawEvents.length,runs:runs.length,agents:agents.length,positions:pos.length,trades:trades.length,marks:rawMarks.length,nodes:nodes.length};return res(200,out)}catch(e){return res(500,{ok:false,error:String((e as any)?.message||e),edge_ms:Date.now()-started})}});
