import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const EXPECTED_HASH="1e96928c7781f339732602234a1047fd510e38de04768d171884166ba5ae91e3";
const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const DEFAULT_ORDER=["conservative","balanced","aggressive","high_conviction","experimental"];

async function sha(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function reply(status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function finite(value:unknown,fallback:number|null=null){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function clamp(value:number,lo=0,hi=100){return Math.max(lo,Math.min(hi,value));}
function unique(values:string[]){return [...new Set(values.filter(Boolean))];}
function dayOf(value:unknown){const d=new Date(String(value||new Date().toISOString()));return Number.isNaN(d.getTime())?new Date().toISOString().slice(0,10):d.toISOString().slice(0,10);}
function weekday(day:string){const n=new Date(day+"T00:00:00Z").getUTCDay();return n>=1&&n<=5;}
function normalized(row:Record<string,unknown>,base:number){const initial=finite(row.initial_equity);const equity=finite(row.equity);return initial&&initial>0&&equity!==null?equity/initial*base:null;}
function maxDrawdown(series:any[]){if(!series.length)return 0;let peak=Number(series[0].normalized_equity),dd=0;for(const x of series){const v=Number(x.normalized_equity);peak=Math.max(peak,v);if(peak>0)dd=Math.min(dd,(v/peak-1)*100);}return dd;}
function moves(series:any[]){let up=0,down=0,neutral=0;for(let i=1;i<series.length;i++){const d=Number(series[i].normalized_equity)-Number(series[i-1].normalized_equity);if(d>1e-9)up++;else if(d<-1e-9)down++;else neutral++;}return {up_days:up,down_days:down,neutral_days:neutral};}

function dynamicRequiredDays(vGap:number,confidence:number,equityGapPct:number){
  const gap=Number.isFinite(vGap)?vGap:0;const conf=clamp(Number.isFinite(confidence)?confidence*100:0)/100;const eq=Number.isFinite(equityGapPct)?equityGapPct:0;
  const days=4+(1-conf)*18+Math.max(0,10-gap)*0.65+Math.max(0,1.5-eq)*1.5;
  return Math.max(2,Math.min(30,Math.ceil(days)));
}

function commonObserved(challenger:any[],champion:any[],since:string){
  const cm=new Map(champion.filter(x=>String(x.date)>=since&&weekday(String(x.date))).map(x=>[String(x.date),x]));
  return challenger.filter(x=>String(x.date)>=since&&weekday(String(x.date))&&cm.has(String(x.date))).map(x=>({date:String(x.date),c:x,h:cm.get(String(x.date))})).sort((a,b)=>a.date.localeCompare(b.date));
}

function readinessCore(challenger:any,champion:any,state:any,cutoff:string|null=null){
  const chSeries=(challenger.daily_equity_30d||[]).filter((x:any)=>!cutoff||String(x.date)<=cutoff);
  const cpSeries=(champion.daily_equity_30d||[]).filter((x:any)=>!cutoff||String(x.date)<=cutoff);
  const chLast=chSeries[chSeries.length-1];const cpLast=cpSeries[cpSeries.length-1];
  if(!chLast||!cpLast)return {readiness:0,eligible:false,reason:"SIN_EVIDENCIA_COMÚN",common_days:0,dynamic_required_days:30,eta_days_low:null,eta_days_high:null};
  const vGap=Number(chLast.v_score||challenger.v_score||200)-Number(cpLast.v_score||champion.v_score||200);
  const equityGapPct=Number(cpLast.normalized_equity)>0?(Number(chLast.normalized_equity)/Number(cpLast.normalized_equity)-1)*100:0;
  const confidence=Math.min(Number(chLast.v_confidence||challenger.v_confidence||0),Number(cpLast.v_confidence||champion.v_confidence||0));
  const guard=Math.max(0,Number(state.risk_guard_pp||10));
  const chDD=maxDrawdown(chSeries);const cpDD=maxDrawdown(cpSeries);const ddExcess=Math.max(0,Math.abs(chDD)-Math.abs(cpDD));
  const riskScore=clamp(100-ddExcess*7);const riskOk=chDD>=cpDD-guard;
  const common=commonObserved(chSeries,cpSeries,String(state.champion_since||"0000-01-01"));
  const recent=common.slice(-10);const leadRatio=recent.length?recent.filter(x=>Number(x.c.normalized_equity)>Number((x.h as any).normalized_equity)).length/recent.length:0;
  let streak=0;for(let i=common.length-1;i>=0;i--){if(Number(common[i].c.normalized_equity)>Number((common[i].h as any).normalized_equity))streak++;else break;}
  const persistence=clamp(100*(0.62*leadRatio+0.23*Math.min(common.length/20,1)+0.15*Math.min(streak/8,1)));
  const qualityAdv=clamp(50+vGap*1.5);const performanceAdv=clamp(50+equityGapPct*4.0);
  const evidenceCh=Number((chLast.v_components||{}).evidence||0);const evidenceCp=Number((cpLast.v_components||{}).evidence||0);const evidence=clamp(Math.min(evidenceCh,evidenceCp));
  const readiness=clamp(0.35*qualityAdv+0.25*performanceAdv+0.20*riskScore+0.12*evidence+0.08*persistence);
  const threshold=Number(state.promotion_threshold||88);const minV=Number(state.min_v_advantage||4);const minConf=Number(state.min_promotion_confidence||0.55);const requiredDays=dynamicRequiredDays(vGap,confidence,equityGapPct);
  const evidenceOk=common.length>=requiredDays;const qualityOk=vGap>=minV;const confidenceOk=confidence>=minConf;const equityOk=equityGapPct>0;
  const eligible=readiness>=threshold&&riskOk&&evidenceOk&&qualityOk&&confidenceOk&&equityOk;
  let status="LEJOS";if(eligible)status="ELEGIBLE";else if(readiness>=80)status="A_PUNTO";else if(readiness>=68)status="CANDIDATO";else if(readiness>=52)status="ACERCÁNDOSE";
  return {readiness,threshold,v_gap:vGap,equity_gap_pct:equityGapPct,confidence,risk_score:riskScore,risk_guard_ok:riskOk,evidence_score:evidence,persistence_score:persistence,common_days:common.length,lead_ratio:leadRatio,streak_days:streak,dynamic_required_days:requiredDays,evidence_ok:evidenceOk,quality_ok:qualityOk,confidence_ok:confidenceOk,equity_ok:equityOk,eligible,status,last_common_day:common.length?common[common.length-1].date:null};
}

function readinessWithEta(challenger:any,champion:any,state:any){
  const current:any=readinessCore(challenger,champion,state,null);const common=commonObserved(challenger.daily_equity_30d||[],champion.daily_equity_30d||[],String(state.champion_since||"0000-01-01"));
  const history:any[]=[];for(const row of common.slice(-6)){const m:any=readinessCore(challenger,champion,state,row.date);history.push({date:row.date,readiness:m.readiness});}
  let velocity:null|number=null;if(history.length>=2){const deltas=[];for(let i=1;i<history.length;i++)deltas.push(history[i].readiness-history[i-1].readiness);velocity=deltas.reduce((a,b)=>a+b,0)/deltas.length;}
  let etaLow:null|number=null,etaHigh:null|number=null,etaText="Evidencia insuficiente para ETA";
  const daysForEvidence=Math.max(0,Number(current.dynamic_required_days||0)-Number(current.common_days||0));
  if(current.eligible){etaLow=0;etaHigh=0;etaText="Elegible para ascenso PAPER";}
  else if(current.v_gap>0&&current.equity_gap_pct>=0&&current.risk_guard_ok){
    let scoreDays:null|number=null;if(current.readiness>=current.threshold)scoreDays=0;else if(velocity!==null&&velocity>0.15)scoreDays=(current.threshold-current.readiness)/velocity;
    if(scoreDays!==null){const eta=Math.max(daysForEvidence,scoreDays);etaLow=Math.max(1,Math.ceil(eta*0.75));etaHigh=Math.max(etaLow,Math.ceil(eta*1.35));etaText=`~${etaLow}–${etaHigh} jornadas si se mantiene la tendencia`;}
    else if(daysForEvidence>0&&current.confidence>=0.35){etaLow=Math.max(1,daysForEvidence);etaHigh=Math.max(etaLow,Math.ceil(daysForEvidence*1.5));etaText=`~${etaLow}–${etaHigh} jornadas si la ventaja se mantiene`;}
  } else if(!current.risk_guard_ok) etaText="ETA bloqueada por riesgo"; else if(current.v_gap<=0) etaText="Sin ventaja de v suficiente"; else if(current.equity_gap_pct<0) etaText="Aún por debajo del Champion en equity";
  return {...current,readiness:Math.round(current.readiness*100)/100,v_gap:Math.round(current.v_gap*100)/100,equity_gap_pct:Math.round(current.equity_gap_pct*100)/100,velocity_per_day:velocity===null?null:Math.round(velocity*100)/100,eta_days_low:etaLow,eta_days_high:etaHigh,eta_text:etaText,readiness_history:history,promotion_policy:String(state.promotion_policy||"dynamic_v1"),promotion_scope:"SIMULATION_LEAGUE_ONLY",automatic_model_promotion:false,live_execution_allowed:false,can_trade:false,real_trading:false};
}

async function ensureState(node:string,body:Record<string,unknown>){
  const {data,error}=await sb.from("radar_simulator_league_state").select("*").eq("origin_node",node).maybeSingle();if(error)throw error;
  const desired={risk_guard_pp:Math.max(0,finite(body.risk_guard_pp,10) as number),promotion_threshold:clamp(finite(body.promotion_threshold,88) as number,50,100),min_promotion_confidence:clamp(finite(body.min_promotion_confidence,0.55) as number,0,1),min_v_advantage:Math.max(0,finite(body.min_v_advantage,4) as number),promotion_policy:String(body.promotion_policy||"dynamic_v1"),updated_at:new Date().toISOString(),real_trading:false};
  if(data){const {data:updated,error:updateError}=await sb.from("radar_simulator_league_state").update(desired).eq("origin_node",node).select("*").single();if(updateError)throw updateError;return updated;}
  const row={origin_node:node,champion_key:String(body.default_champion_key||"champion"),challenger_order:Array.isArray(body.challenger_order)?body.challenger_order:DEFAULT_ORDER,champion_since:new Date().toISOString().slice(0,10),promotion_days:10,last_promotion_day:null,...desired};
  const {data:created,error:createError}=await sb.from("radar_simulator_league_state").insert(row).select("*").single();if(createError)throw createError;return created;
}

async function buildStatus(node:string,days:number,base:number){
  const window=Math.max(1,Math.min(90,Math.trunc(days||30)));const sinceDate=new Date(Date.now()-window*86400000).toISOString().slice(0,10);
  const {data:state,error:stateError}=await sb.from("radar_simulator_league_state").select("*").eq("origin_node",node).maybeSingle();if(stateError)throw stateError;
  const leagueState=state||{champion_key:"champion",challenger_order:DEFAULT_ORDER,champion_since:sinceDate,risk_guard_pp:10,promotion_threshold:88,min_promotion_confidence:0.55,min_v_advantage:4,promotion_policy:"dynamic_v1",last_promotion_day:null};
  const {data:rows,error}=await sb.from("radar_simulator_league_daily").select("origin_node,competitor_key,day,observed_at,display_name,risk_rank,risk_label,strategy_kind,initial_equity,equity,cash,invested,drawdown_pct,target_invested_pct,v_score,v_band,v_confidence,v_raw_quality,v_components,score_semantics,promotion_readiness,promotion_detail").eq("origin_node",node).gte("day",sinceDate).order("day",{ascending:true});if(error)throw error;
  const grouped=new Map<string,any[]>();for(const raw of rows||[]){const key=String(raw.competitor_key);const n=normalized(raw,base);if(n===null)continue;const item={date:String(raw.day),observed_at:raw.observed_at,equity:Number(raw.equity),normalized_equity:n,cash:finite(raw.cash),invested:finite(raw.invested),drawdown_pct:finite(raw.drawdown_pct,0),initial_equity:Number(raw.initial_equity),v_score:finite(raw.v_score,200),v_band:String(raw.v_band||"NEUTRA"),v_confidence:finite(raw.v_confidence,0),v_raw_quality:finite(raw.v_raw_quality,50),v_components:raw.v_components||{},score_semantics:String(raw.score_semantics||"OBSERVED_PAPER_DECISION_QUALITY_PROXY")};if(!grouped.has(key))grouped.set(key,[]);grouped.get(key)!.push(item);}
  const allKeys=[...grouped.keys()];const championKey=String(leagueState.champion_key||"champion");const configuredOrder=Array.isArray(leagueState.challenger_order)?leagueState.challenger_order.map(String):DEFAULT_ORDER;const challengerOrder=unique([...configuredOrder,...allKeys.filter(k=>k!==championKey)]).filter(k=>k!==championKey);const roleOrder=[championKey,...challengerOrder];const competitors:any[]=[];
  for(const key of allKeys){const series=grouped.get(key)||[];if(!series.length)continue;const current=series[series.length-1];const raw=(rows||[]).filter(r=>String(r.competitor_key)===key).slice(-1)[0] as Record<string,unknown>;const first=series[0];const change=first.normalized_equity?((current.normalized_equity/first.normalized_equity)-1)*100:null;const mv=moves(series);const investedPct=current.equity>0&&current.invested!==null?Number(current.invested)/current.equity*100:null;const previous=series.length>1?series[series.length-2]:null;competitors.push({competitor_key:key,display_name:String(raw?.display_name||key),risk_rank:finite(raw?.risk_rank,0),risk_label:String(raw?.risk_label||"RIESGO ?"),strategy_kind:String(raw?.strategy_kind||"PAPER_CHALLENGER"),league_role:key===championKey?"CHAMPION":`CHALLENGER ${Math.max(1,roleOrder.indexOf(key))}`,display_base_equity:base,current_equity:current.normalized_equity,current_real_equity:current.equity,period_change_pct:change,month_high:Math.max(...series.map(x=>x.normalized_equity)),month_low:Math.min(...series.map(x=>x.normalized_equity)),max_drawdown_pct:maxDrawdown(series),invested_pct:investedPct,target_invested_pct:finite(raw?.target_invested_pct),observed_days:series.length,aciertos:mv.up_days,errores:mv.down_days,neutros:mv.neutral_days,v_score:Number(current.v_score||200),v_band:String(current.v_band||"NEUTRA"),v_confidence:Number(current.v_confidence||0),v_raw_quality:Number(current.v_raw_quality||50),v_components:current.v_components||{},v_trend:previous?Number(current.v_score||200)-Number(previous.v_score||200):0,score_semantics:current.score_semantics,daily_equity_30d:series});}
  const ranking=[...competitors].sort((a,b)=>b.current_equity-a.current_equity).map((x,i)=>({...x,rank:i+1}));const byKey=new Map(ranking.map(x=>[x.competitor_key,x]));const champion=byKey.get(championKey);const watches:any[]=[];
  if(champion){for(const row of ranking){if(row.competitor_key===championKey)continue;watches.push({competitor_key:row.competitor_key,display_name:row.display_name,league_role:row.league_role,risk_label:row.risk_label,current_equity:row.current_equity,champion_equity:champion.current_equity,v_score:row.v_score,champion_v_score:champion.v_score,...readinessWithEta(row,champion,leagueState)});}}
  watches.sort((a,b)=>Number(b.readiness)-Number(a.readiness)||Number(b.v_gap)-Number(a.v_gap)||Number(b.current_equity)-Number(a.current_equity));
  const {data:events,error:eventError}=await sb.from("radar_simulator_league_events").select("day,from_key,to_key,reason,payload,created_at").eq("origin_node",node).order("created_at",{ascending:false}).limit(10);if(eventError)throw eventError;
  return {ok:true,status:ranking.length?"ACTIVE":"WAITING_FOR_FIRST_SNAPSHOT",window_days:window,display_base_equity:base,source:"SUPABASE_OBSERVED_PAPER_SIMULATION_LEAGUE",champion_key:championKey,champion_since:String(leagueState.champion_since||sinceDate),promotion_threshold:Number(leagueState.promotion_threshold||88),min_promotion_confidence:Number(leagueState.min_promotion_confidence||0.55),min_v_advantage:Number(leagueState.min_v_advantage||4),risk_guard_pp:Number(leagueState.risk_guard_pp||10),promotion_policy:String(leagueState.promotion_policy||"dynamic_v1"),leaderboard:ranking,promotion_watch:watches,best_promotion_watch:watches[0]||null,recent_promotions:events||[],backfilled:false,reconstructed:false,promotion_scope:"SIMULATION_LEAGUE_ONLY",automatic_model_promotion:false,live_execution_allowed:false,can_trade:false,real_trading:false};
}

async function persist(node:string,body:Record<string,unknown>){
  const state=await ensureState(node,body);const competitors=Array.isArray(body.competitors)?(body.competitors as Record<string,unknown>[]).slice(0,50):[];
  const rows=competitors.map(x=>({origin_node:node,competitor_key:String(x.competitor_key||""),day:dayOf(x.observed_at),observed_at:String(x.observed_at||new Date().toISOString()),display_name:String(x.display_name||x.competitor_key||"Unknown"),risk_rank:Math.trunc(finite(x.risk_rank,0) as number),risk_label:String(x.risk_label||"RIESGO ?"),strategy_kind:String(x.strategy_kind||"PAPER_CHALLENGER"),initial_equity:finite(x.initial_equity),equity:finite(x.equity),cash:finite(x.cash),invested:finite(x.invested),drawdown_pct:finite(x.drawdown_pct,0),target_invested_pct:finite(x.target_invested_pct),v_score:Math.max(0,Math.min(400,Math.round(finite(x.v_score,200) as number))),v_band:String(x.v_band||"NEUTRA"),v_confidence:clamp(finite(x.v_confidence,0) as number,0,1),v_raw_quality:clamp(finite(x.v_raw_quality,50) as number),v_components:x.v_components&&typeof x.v_components==="object"?x.v_components:{},score_semantics:String(x.score_semantics||"OBSERVED_PAPER_DECISION_QUALITY_PROXY"),real_trading:false})).filter(x=>x.competitor_key&&x.initial_equity!==null&&(x.initial_equity as number)>0&&x.equity!==null&&(x.equity as number)>=0);
  if(rows.length){const {error}=await sb.from("radar_simulator_league_daily").upsert(rows,{onConflict:"origin_node,competitor_key,day"});if(error)throw error;}
  let status:any=await buildStatus(node,30,Math.max(1,finite(body.display_base_equity,1000) as number));
  for(const watch of status.promotion_watch||[]){const detail={v_gap:watch.v_gap,equity_gap_pct:watch.equity_gap_pct,confidence:watch.confidence,risk_score:watch.risk_score,evidence_score:watch.evidence_score,persistence_score:watch.persistence_score,dynamic_required_days:watch.dynamic_required_days,common_days:watch.common_days,eta_days_low:watch.eta_days_low,eta_days_high:watch.eta_days_high,eta_text:watch.eta_text,status:watch.status,promotion_policy:watch.promotion_policy,eligible:watch.eligible,real_trading:false};await sb.from("radar_simulator_league_daily").update({promotion_readiness:watch.readiness,promotion_detail:detail}).eq("origin_node",node).eq("competitor_key",watch.competitor_key).eq("day",dayOf(new Date().toISOString()));}
  const eligible=(status.promotion_watch||[]).filter((x:any)=>x.eligible);let promotion:any=null;const today=new Date().toISOString().slice(0,10);
  if(eligible.length&&String(state.last_promotion_day||"")!==today){const next=eligible.sort((a:any,b:any)=>Number(b.readiness)-Number(a.readiness)||Number(b.v_gap)-Number(a.v_gap))[0];const old=String(state.champion_key||"champion");const existing=Array.isArray(state.challenger_order)?state.challenger_order.map(String):DEFAULT_ORDER;const order=unique([old,...existing.filter((x:string)=>x!==old&&x!==next.competitor_key),...rows.map(x=>x.competitor_key).filter(x=>x!==old&&x!==next.competitor_key)]);const update={champion_key:next.competitor_key,challenger_order:order,champion_since:today,last_promotion_day:today,updated_at:new Date().toISOString(),real_trading:false};const {error:updateError}=await sb.from("radar_simulator_league_state").update(update).eq("origin_node",node);if(updateError)throw updateError;promotion={from_key:old,to_key:next.competitor_key,day:today,reason:`Readiness ${Number(next.readiness).toFixed(1)}/100; v ${next.v_score} vs ${next.champion_v_score}; evidencia dinámica ${next.common_days}/${next.dynamic_required_days}; riesgo OK`,payload:{readiness:next.readiness,v_gap:next.v_gap,equity_gap_pct:next.equity_gap_pct,confidence:next.confidence,dynamic_required_days:next.dynamic_required_days,common_days:next.common_days,promotion_policy:String(state.promotion_policy||"dynamic_v1"),promotion_scope:"SIMULATION_LEAGUE_ONLY",automatic_model_promotion:false,can_trade:false,real_trading:false},real_trading:false};const {error:eventError}=await sb.from("radar_simulator_league_events").insert({origin_node:node,...promotion});if(eventError)throw eventError;status=await buildStatus(node,30,Math.max(1,finite(body.display_base_equity,1000) as number));}
  return {ok:true,persisted:rows.length,promotion,league:status,automatic_model_promotion:false,live_execution_allowed:false,can_trade:false,real_trading:false};
}

Deno.serve(async(req)=>{try{const token=req.headers.get("x-radar-token")||"";if(!token||await sha(token)!==EXPECTED_HASH)return reply(401,{ok:false,error:"unauthorized"});if(req.method!=="POST")return reply(405,{ok:false,error:"method_not_allowed"});const body=await req.json() as Record<string,unknown>;const node=String(body.node_id||"cloud-primary");const action=String(body.action||"simulator_league");if(action==="persist_simulator_league")return reply(200,await persist(node,body));if(action==="simulator_league")return reply(200,await buildStatus(node,Math.trunc(finite(body.days,30) as number),Math.max(1,finite(body.display_base_equity,1000) as number)));return reply(400,{ok:false,error:"unsupported_action",automatic_model_promotion:false,can_trade:false,real_trading:false});}catch(error){return reply(500,{ok:false,error:String((error as Error)?.message||error),backfilled:false,reconstructed:false,automatic_model_promotion:false,live_execution_allowed:false,can_trade:false,real_trading:false});}});
