import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const EXPECTED_HASH="1e96928c7781f339732602234a1047fd510e38de04768d171884166ba5ae91e3";
const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const DEFAULT_ORDER=["conservative","balanced","aggressive","high_conviction","experimental"];

async function sha(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function reply(status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}
function dayOf(value:unknown){const d=new Date(String(value||new Date().toISOString()));return Number.isNaN(d.getTime())?new Date().toISOString().slice(0,10):d.toISOString().slice(0,10);}
function finite(value:unknown,fallback:number|null=null){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function normalized(row:Record<string,unknown>,base:number){const initial=finite(row.initial_equity);const equity=finite(row.equity);return initial&&initial>0&&equity!==null?equity/initial*base:null;}
function maxDrawdown(series:{normalized_equity:number}[]){if(!series.length)return 0;let peak=series[0].normalized_equity,dd=0;for(const x of series){peak=Math.max(peak,x.normalized_equity);if(peak>0)dd=Math.min(dd,(x.normalized_equity/peak-1)*100);}return dd;}
function moves(series:{normalized_equity:number}[]){let up=0,down=0,neutral=0;for(let i=1;i<series.length;i++){const d=series[i].normalized_equity-series[i-1].normalized_equity;if(d>1e-9)up++;else if(d< -1e-9)down++;else neutral++;}return {up_days:up,down_days:down,neutral_days:neutral};}
function unique(values:string[]){return [...new Set(values.filter(Boolean))];}
function weekday(day:string){const n=new Date(day+"T00:00:00Z").getUTCDay();return n>=1&&n<=5;}

async function ensureState(node:string,body:Record<string,unknown>){const {data,error}=await sb.from("radar_simulator_league_state").select("*").eq("origin_node",node).maybeSingle();if(error)throw error;if(data)return data;const row={origin_node:node,champion_key:String(body.default_champion_key||"champion"),challenger_order:Array.isArray(body.challenger_order)?body.challenger_order:DEFAULT_ORDER,champion_since:new Date().toISOString().slice(0,10),promotion_days:Math.max(2,Math.trunc(finite(body.promotion_days,10) as number)),risk_guard_pp:Math.max(0,finite(body.risk_guard_pp,10) as number),real_trading:false};const {data:created,error:createError}=await sb.from("radar_simulator_league_state").insert(row).select("*").single();if(createError)throw createError;return created;}

function streakAbove(challenger:any[],champion:any[],since:string){const cm=new Map(champion.filter(x=>x.date>=since&&weekday(x.date)).map(x=>[x.date,x.normalized_equity]));const common=challenger.filter(x=>x.date>=since&&weekday(x.date)&&cm.has(x.date)).map(x=>({date:x.date,c:x.normalized_equity,h:Number(cm.get(x.date))})).sort((a,b)=>a.date.localeCompare(b.date));let streak=0;for(let i=common.length-1;i>=0;i--){if(common[i].c>common[i].h)streak++;else break;}return {streak,last_common_day:common.length?common[common.length-1].date:null,common_days:common.length};}

async function buildStatus(node:string,days:number,base:number){const window=Math.max(1,Math.min(90,Math.trunc(days||30)));const sinceDate=new Date(Date.now()-window*86400000).toISOString().slice(0,10);const {data:state,error:stateError}=await sb.from("radar_simulator_league_state").select("*").eq("origin_node",node).maybeSingle();if(stateError)throw stateError;const leagueState=state||{champion_key:"champion",challenger_order:DEFAULT_ORDER,champion_since:sinceDate,promotion_days:10,risk_guard_pp:10,last_promotion_day:null};const {data:rows,error}=await sb.from("radar_simulator_league_daily").select("origin_node,competitor_key,day,observed_at,display_name,risk_rank,risk_label,strategy_kind,initial_equity,equity,cash,invested,drawdown_pct,target_invested_pct").eq("origin_node",node).gte("day",sinceDate).order("day",{ascending:true});if(error)throw error;
 const grouped=new Map<string,any[]>();for(const raw of rows||[]){const key=String(raw.competitor_key);const n=normalized(raw,base);if(n===null)continue;const item={date:String(raw.day),observed_at:raw.observed_at,equity:Number(raw.equity),normalized_equity:n,cash:finite(raw.cash),invested:finite(raw.invested),drawdown_pct:finite(raw.drawdown_pct,0),initial_equity:Number(raw.initial_equity)};if(!grouped.has(key))grouped.set(key,[]);grouped.get(key)!.push(item);}
 const allKeys=[...grouped.keys()];const championKey=String(leagueState.champion_key||"champion");const configuredOrder=Array.isArray(leagueState.challenger_order)?leagueState.challenger_order.map(String):DEFAULT_ORDER;const challengerOrder=unique([...configuredOrder,...allKeys.filter(k=>k!==championKey)]).filter(k=>k!==championKey);const roleOrder=[championKey,...challengerOrder];const competitors:any[]=[];
 for(const key of allKeys){const series=grouped.get(key)||[];if(!series.length)continue;const current=series[series.length-1];const raw=(rows||[]).filter(r=>String(r.competitor_key)===key).slice(-1)[0] as Record<string,unknown>;const first=series[0];const change=first.normalized_equity?((current.normalized_equity/first.normalized_equity)-1)*100:null;const mv=moves(series);const investedPct=current.equity>0&&current.invested!==null?Number(current.invested)/current.equity*100:null;competitors.push({competitor_key:key,display_name:String(raw?.display_name||key),risk_rank:finite(raw?.risk_rank,0),risk_label:String(raw?.risk_label||"RIESGO ?"),strategy_kind:String(raw?.strategy_kind||"PAPER_CHALLENGER"),league_role:key===championKey?"CHAMPION":`CHALLENGER ${Math.max(1,roleOrder.indexOf(key))}`,display_base_equity:base,current_equity:current.normalized_equity,current_real_equity:current.equity,period_change_pct:change,month_high:Math.max(...series.map(x=>x.normalized_equity)),month_low:Math.min(...series.map(x=>x.normalized_equity)),max_drawdown_pct:maxDrawdown(series),invested_pct:investedPct,target_invested_pct:finite(raw?.target_invested_pct),observed_days:series.length,aciertos:mv.up_days,errores:mv.down_days,neutros:mv.neutral_days,daily_equity_30d:series});}
 const ranking=[...competitors].sort((a,b)=>b.current_equity-a.current_equity).map((x,i)=>({...x,rank:i+1}));const byKey=new Map(ranking.map(x=>[x.competitor_key,x]));const champion=byKey.get(championKey);const promotionDays=Math.max(2,Number(leagueState.promotion_days||10));const guard=Math.max(0,Number(leagueState.risk_guard_pp||10));const championSince=String(leagueState.champion_since||sinceDate);const latestDay=ranking.reduce((m,x)=>x.daily_equity_30d.length&&x.daily_equity_30d[x.daily_equity_30d.length-1].date>m?x.daily_equity_30d[x.daily_equity_30d.length-1].date:m,"");const watches:any[]=[];
 if(champion){for(const row of ranking){if(row.competitor_key===championKey)continue;const s=streakAbove(row.daily_equity_30d,champion.daily_equity_30d,championSince);const riskOk=row.max_drawdown_pct>=champion.max_drawdown_pct-guard;const fresh=Boolean(s.last_common_day&&s.last_common_day===latestDay);watches.push({competitor_key:row.competitor_key,display_name:row.display_name,league_role:row.league_role,risk_label:row.risk_label,streak_days:s.streak,required_days:promotionDays,days_remaining:Math.max(0,promotionDays-s.streak),risk_guard_ok:riskOk,risk_guard_pp:guard,fresh_common_day:fresh,eligible:s.streak>=promotionDays&&riskOk&&fresh,current_equity:row.current_equity,champion_equity:champion.current_equity,common_days:s.common_days,last_common_day:s.last_common_day,promotion_scope:"SIMULATION_LEAGUE_ONLY",automatic_model_promotion:false,can_trade:false,real_trading:false});}}
 watches.sort((a,b)=>b.streak_days-a.streak_days||b.current_equity-a.current_equity);const {data:events,error:eventError}=await sb.from("radar_simulator_league_events").select("day,from_key,to_key,reason,created_at").eq("origin_node",node).order("created_at",{ascending:false}).limit(10);if(eventError)throw eventError;
 return {ok:true,status:ranking.length?"ACTIVE":"WAITING_FOR_FIRST_SNAPSHOT",window_days:window,display_base_equity:base,source:"SUPABASE_OBSERVED_PAPER_SIMULATION_LEAGUE",champion_key:championKey,champion_since:championSince,promotion_days:promotionDays,risk_guard_pp:guard,leaderboard:ranking,promotion_watch:watches,best_promotion_watch:watches[0]||null,recent_promotions:events||[],backfilled:false,reconstructed:false,promotion_scope:"SIMULATION_LEAGUE_ONLY",automatic_model_promotion:false,live_execution_allowed:false,can_trade:false,real_trading:false};}

async function persist(node:string,body:Record<string,unknown>){const state=await ensureState(node,body);const competitors=Array.isArray(body.competitors)?(body.competitors as Record<string,unknown>[]).slice(0,50):[];const rows=competitors.map(x=>({origin_node:node,competitor_key:String(x.competitor_key||""),day:dayOf(x.observed_at),observed_at:String(x.observed_at||new Date().toISOString()),display_name:String(x.display_name||x.competitor_key||"Unknown"),risk_rank:Math.trunc(finite(x.risk_rank,0) as number),risk_label:String(x.risk_label||"RIESGO ?"),strategy_kind:String(x.strategy_kind||"PAPER_CHALLENGER"),initial_equity:finite(x.initial_equity),equity:finite(x.equity),cash:finite(x.cash),invested:finite(x.invested),drawdown_pct:finite(x.drawdown_pct,0),target_invested_pct:finite(x.target_invested_pct),real_trading:false})).filter(x=>x.competitor_key&&x.initial_equity!==null&&(x.initial_equity as number)>0&&x.equity!==null&&(x.equity as number)>=0);if(rows.length){const {error}=await sb.from("radar_simulator_league_daily").upsert(rows,{onConflict:"origin_node,competitor_key,day"});if(error)throw error;}
 let status=await buildStatus(node,30,Math.max(1,finite(body.display_base_equity,1000) as number));const eligible=(status.promotion_watch as any[]).filter(x=>x.eligible);let promotion:any=null;const today=new Date().toISOString().slice(0,10);if(eligible.length&&String(state.last_promotion_day||"")!==today){const next=eligible.sort((a,b)=>b.streak_days-a.streak_days||b.current_equity-a.current_equity)[0];const old=String(state.champion_key||"champion");const existing=Array.isArray(state.challenger_order)?state.challenger_order.map(String):DEFAULT_ORDER;const order=unique([old,...existing.filter((x:string)=>x!==old&&x!==next.competitor_key),...rows.map(x=>x.competitor_key).filter(x=>x!==old&&x!==next.competitor_key)]);const update={champion_key:next.competitor_key,challenger_order:order,champion_since:today,last_promotion_day:today,updated_at:new Date().toISOString(),real_trading:false};const {error:updateError}=await sb.from("radar_simulator_league_state").update(update).eq("origin_node",node);if(updateError)throw updateError;promotion={from_key:old,to_key:next.competitor_key,day:today,reason:`${next.streak_days} jornadas sobre Champion; risk guard OK`,payload:{streak_days:next.streak_days,risk_guard_pp:status.risk_guard_pp,promotion_scope:"SIMULATION_LEAGUE_ONLY"},real_trading:false};const {error:eventError}=await sb.from("radar_simulator_league_events").insert({origin_node:node,...promotion});if(eventError)throw eventError;status=await buildStatus(node,30,Math.max(1,finite(body.display_base_equity,1000) as number));}
 return {ok:true,persisted:rows.length,promotion,league:status,automatic_model_promotion:false,can_trade:false,real_trading:false};}

Deno.serve(async(req)=>{try{const token=req.headers.get("x-radar-token")||"";if(!token||await sha(token)!==EXPECTED_HASH)return reply(401,{ok:false,error:"unauthorized"});if(req.method!=="POST")return reply(405,{ok:false,error:"method_not_allowed"});const body=await req.json() as Record<string,unknown>;const node=String(body.node_id||"cloud-primary");const action=String(body.action||"simulator_league");if(action==="persist_simulator_league")return reply(200,await persist(node,body));if(action==="simulator_league")return reply(200,await buildStatus(node,Math.trunc(finite(body.days,30) as number),Math.max(1,finite(body.display_base_equity,1000) as number)));return reply(400,{ok:false,error:"unsupported_action",real_trading:false});}catch(error){return reply(500,{ok:false,error:String((error as Error)?.message||error),automatic_model_promotion:false,can_trade:false,real_trading:false});}});
