-- Durable autonomous PAPER forward-maturity ledger.
-- No calendar/backfill/downtime credit. REAL_TRADING remains false.
create table if not exists public.radar_paper_forward_maturity_ledger (
  id bigint generated by default as identity primary key,
  interval_id text not null unique,
  session_id text not null,
  lease_owner text,
  lease_epoch bigint,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  duration_seconds bigint generated always as (greatest(0, floor(extract(epoch from (ended_at-started_at)))::bigint)) stored,
  healthy boolean not null default false,
  exact_restore boolean not null default false,
  singleton boolean not null default false,
  persistence_reconciled boolean not null default false,
  market_data_ok boolean not null default false,
  backfilled boolean not null default false,
  downtime boolean not null default false,
  state_hash text,
  reason text,
  source text not null default 'runtime',
  real_trading boolean not null default false,
  created_at timestamptz not null default now(),
  constraint paper_maturity_positive_interval check (ended_at > started_at),
  constraint paper_maturity_real_trading_false check (real_trading = false),
  constraint paper_maturity_no_backfill_credit check (not (healthy and backfilled)),
  constraint paper_maturity_no_downtime_credit check (not (healthy and downtime))
);
create index if not exists radar_paper_forward_maturity_started_idx on public.radar_paper_forward_maturity_ledger(started_at);
create index if not exists radar_paper_forward_maturity_session_idx on public.radar_paper_forward_maturity_ledger(session_id, started_at);
alter table public.radar_paper_forward_maturity_ledger enable row level security;
revoke all on public.radar_paper_forward_maturity_ledger from anon, authenticated;

create or replace function public.radar_paper_valid_forward_hours()
returns table(valid_forward_seconds bigint, valid_forward_hours numeric, qualifying_intervals bigint, first_valid_at timestamptz, last_valid_at timestamptz)
language sql security definer set search_path=public as $$
with eligible as (
  select *, lag(ended_at) over(order by started_at, ended_at, id) as prior_end
  from public.radar_paper_forward_maturity_ledger
  where healthy and exact_restore and singleton and persistence_reconciled and market_data_ok
    and not backfilled and not downtime and real_trading=false
), non_overlapping as (
  select * from eligible where prior_end is null or started_at >= prior_end
)
select coalesce(sum(duration_seconds),0)::bigint,
       round((coalesce(sum(duration_seconds),0)::numeric/3600),6),
       count(*)::bigint,min(started_at),max(ended_at)
from non_overlapping;
$$;
revoke all on function public.radar_paper_valid_forward_hours() from public;
grant execute on function public.radar_paper_valid_forward_hours() to service_role;

create or replace function public.radar_append_paper_maturity_interval(
  p_interval_id text,p_session_id text,p_lease_owner text,p_lease_epoch bigint,
  p_started_at timestamptz,p_ended_at timestamptz,p_healthy boolean,p_exact_restore boolean,
  p_singleton boolean,p_persistence_reconciled boolean,p_market_data_ok boolean,
  p_backfilled boolean,p_downtime boolean,p_state_hash text,p_reason text,p_source text default 'runtime'
) returns public.radar_paper_forward_maturity_ledger
language plpgsql security definer set search_path=public as $$
declare outrow public.radar_paper_forward_maturity_ledger;
declare lease_ok boolean := false;
begin
  if p_interval_id is null or length(trim(p_interval_id))=0 then raise exception 'interval_id required'; end if;
  if p_session_id is null or length(trim(p_session_id))=0 then raise exception 'session_id required'; end if;
  if p_lease_owner is null or length(trim(p_lease_owner))=0 then raise exception 'lease_owner required'; end if;
  if p_ended_at <= p_started_at then raise exception 'invalid interval'; end if;
  if p_ended_at > now() + interval '5 seconds' then raise exception 'future interval forbidden'; end if;
  if p_ended_at - p_started_at > interval '15 minutes' then raise exception 'interval too large'; end if;
  if p_healthy and (p_backfilled or p_downtime) then raise exception 'invalid healthy credit flags'; end if;
  if p_healthy and (p_state_hash is null or length(trim(p_state_hash)) < 16) then raise exception 'healthy interval requires state_hash'; end if;
  select exists(select 1 from public.radar_paper_runtime_lease l where l.owner_id=p_lease_owner and l.session_id=p_session_id and l.epoch=p_lease_epoch and l.real_trading=false and l.expires_at >= now()) into lease_ok;
  if not lease_ok then raise exception 'active matching lease required'; end if;
  if exists(select 1 from public.radar_paper_forward_maturity_ledger where tstzrange(started_at, ended_at, '[)') && tstzrange(p_started_at, p_ended_at, '[)') and interval_id <> p_interval_id) then raise exception 'overlapping interval'; end if;
  insert into public.radar_paper_forward_maturity_ledger(interval_id,session_id,lease_owner,lease_epoch,started_at,ended_at,healthy,exact_restore,singleton,persistence_reconciled,market_data_ok,backfilled,downtime,state_hash,reason,source,real_trading)
  values(p_interval_id,p_session_id,p_lease_owner,p_lease_epoch,p_started_at,p_ended_at,p_healthy,p_exact_restore,p_singleton,p_persistence_reconciled,p_market_data_ok,p_backfilled,p_downtime,p_state_hash,p_reason,coalesce(p_source,'runtime'),false)
  on conflict(interval_id) do nothing returning * into outrow;
  if outrow.id is null then select * into outrow from public.radar_paper_forward_maturity_ledger where interval_id=p_interval_id; end if;
  return outrow;
end;
$$;
revoke all on function public.radar_append_paper_maturity_interval(text,text,text,bigint,timestamptz,timestamptz,boolean,boolean,boolean,boolean,boolean,boolean,boolean,text,text,text) from public;
grant execute on function public.radar_append_paper_maturity_interval(text,text,text,bigint,timestamptz,timestamptz,boolean,boolean,boolean,boolean,boolean,boolean,boolean,text,text,text) to service_role;
