-- Brain Evolution v3 governance; service-role sync only; real trading remains OFF.
alter table public.brain_lineages add column if not exists family text;
alter table public.brain_lineages add column if not exists mutation jsonb not null default '{}'::jsonb;
alter table public.brain_lineages add column if not exists specialization jsonb not null default '{}'::jsonb;
alter table public.brain_lineages add column if not exists training_method text;
alter table public.brain_lineages add column if not exists features jsonb not null default '[]'::jsonb;
alter table public.brain_lineages add column if not exists updated_at timestamptz;
alter table public.brain_evidence add column if not exists evidence_key text;
create unique index if not exists brain_evidence_key_uq on public.brain_evidence(evidence_key) where evidence_key is not null;
alter table public.brain_transfer add column if not exists regime text;
alter table public.brain_transfer add column if not exists horizon text;
create unique index if not exists brain_transfer_dimensions_uq on public.brain_transfer(lineage,coalesce(regime,''),coalesce(horizon,''));
alter table public.brain_vault_registry add column if not exists vault_type text not null default 'rotating';
alter table public.brain_vault_registry add column if not exists candidate_evaluated text;
alter table public.brain_vault_registry add column if not exists result jsonb;
alter table public.brain_vault_registry add column if not exists reuse_penalty double precision not null default 0;

create table if not exists public.brain_vault_events(id bigint generated by default as identity primary key,created_at timestamptz not null,vault_key text not null,lineage text,action text not null,purpose text not null,result jsonb,epistemic_penalty double precision not null default 0,origin_node text,origin_id text,unique(origin_node,origin_id));
create table if not exists public.brain_shadow_predictions(id bigint generated by default as identity primary key,prediction_key text not null unique,created_at timestamptz not null,lineage text not null,symbol text not null,horizon text not null,cutoff timestamptz not null,due_at timestamptz not null,score double precision not null,confidence double precision not null,features jsonb not null default '{}'::jsonb,provenance jsonb not null default '{}'::jsonb,outcome double precision,evaluated_at timestamptz,origin_node text,origin_id text,check ((outcome is null and evaluated_at is null) or (outcome is not null and evaluated_at is not null)));
create table if not exists public.brain_generation_runs(id bigint generated by default as identity primary key,created_at timestamptz not null,generation integer not null,champion text,candidates_tested integer not null default 0,candidates_surviving integer not null default 0,status text,configuration jsonb not null default '{}'::jsonb,result jsonb,origin_node text,origin_id text,unique(origin_node,origin_id));
alter table public.brain_hall_of_fame add column if not exists category text not null default 'general';
alter table public.brain_graveyard add column if not exists failed_regime text;
alter table public.brain_graveyard add column if not exists failed_horizon text;

alter table public.brain_vault_events enable row level security;
alter table public.brain_shadow_predictions enable row level security;
alter table public.brain_generation_runs enable row level security;
create index if not exists brain_shadow_due_idx on public.brain_shadow_predictions(evaluated_at,due_at);
create index if not exists brain_evidence_lineage_idx on public.brain_evidence(lineage,tier,horizon);

insert into public.brain_vault_registry(vault_key,status,vault_type,metadata)
values('deep_final_test','sealed','deep','{}'::jsonb)
on conflict(vault_key) do update set vault_type='deep';
