-- Pre-1.6 evidence v4: operational checkpoint continuity + immutable PIT decision envelopes.
-- PAPER/SHADOW only. No table can authorize real trading.

create table if not exists public.radar_pre160_evidence_checkpoints (
  id bigint generated by default as identity primary key,
  origin_node text not null,
  observed_at timestamptz not null,
  snapshot_hash text not null,
  prev_hash text,
  record_hash text not null,
  snapshot jsonb not null default '{}'::jsonb,
  real_trading boolean not null default false check (real_trading = false),
  unique(origin_node, snapshot_hash)
);
create index if not exists idx_pre160_checkpoint_node_id on public.radar_pre160_evidence_checkpoints(origin_node,id);

create table if not exists public.radar_pre160_decision_envelopes (
  id bigint generated by default as identity primary key,
  origin_node text not null,
  source_key text not null,
  trade_id bigint not null,
  trade_ts timestamptz not null,
  competitor_key text not null,
  strategy_identity text not null,
  strategy_version text,
  decision_fingerprint text not null,
  symbol text not null,
  side text not null,
  regime_ts timestamptz,
  regime text,
  regime_confidence double precision,
  benchmark_snapshot jsonb not null default '{}'::jsonb,
  cost_snapshot jsonb not null default '{}'::jsonb,
  provider_snapshot jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  envelope_hash text not null,
  payload jsonb not null default '{}'::jsonb,
  real_trading boolean not null default false check (real_trading = false),
  unique(origin_node, source_key, trade_id),
  unique(origin_node, envelope_hash)
);
create index if not exists idx_pre160_envelope_node_ts on public.radar_pre160_decision_envelopes(origin_node,trade_ts);

create table if not exists public.radar_pre160_guard_state (
  origin_node text primary key,
  updated_at timestamptz not null default now(),
  last_checkpoint_id bigint,
  last_checkpoint_hash text,
  consecutive_degraded_days integer not null default 0,
  cooldown_until date,
  payload jsonb not null default '{}'::jsonb,
  real_trading boolean not null default false check (real_trading = false)
);

alter table public.radar_pre160_evidence_checkpoints enable row level security;
alter table public.radar_pre160_decision_envelopes enable row level security;
alter table public.radar_pre160_guard_state enable row level security;

revoke all on public.radar_pre160_evidence_checkpoints from anon, authenticated;
revoke all on public.radar_pre160_decision_envelopes from anon, authenticated;
revoke all on public.radar_pre160_guard_state from anon, authenticated;
grant select,insert,update,delete on public.radar_pre160_evidence_checkpoints to service_role;
grant select,insert,update,delete on public.radar_pre160_decision_envelopes to service_role;
grant select,insert,update,delete on public.radar_pre160_guard_state to service_role;
grant usage,select on sequence public.radar_pre160_evidence_checkpoints_id_seq to service_role;
grant usage,select on sequence public.radar_pre160_decision_envelopes_id_seq to service_role;
