create table if not exists public.historical_lab_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  base_model text not null,
  candidate_version text,
  symbols integer not null,
  observations integer not null,
  folds integer not null,
  positive_folds integer not null,
  mean_gain double precision,
  median_gain double precision,
  test_objective_champion double precision,
  test_objective_challenger double precision,
  accepted boolean not null default false,
  promoted boolean not null default false,
  candidate_weights jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  origin_node text,
  origin_id bigint,
  unique(origin_node, origin_id)
);
create table if not exists public.historical_fold_results (
  id bigint generated by default as identity primary key,
  run_origin_node text not null,
  run_origin_id bigint not null,
  fold_no integer not null,
  train_start timestamptz,
  train_end timestamptz,
  validation_start timestamptz,
  validation_end timestamptz,
  observations_train integer not null,
  observations_validation integer not null,
  champion_objective double precision,
  challenger_objective double precision,
  gain double precision,
  challenger_weights jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  origin_node text,
  origin_id bigint,
  unique(origin_node, origin_id)
);
create index if not exists idx_historical_lab_runs_created on public.historical_lab_runs(created_at desc);
create index if not exists idx_historical_fold_run on public.historical_fold_results(run_origin_node,run_origin_id,fold_no);
alter table public.historical_lab_runs enable row level security;
alter table public.historical_fold_results enable row level security;
